let myProducts = [
  {
    id: 1,
    primaryImage: "https://i.ibb.co/9TD2kHv/1-black-dress.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/JyhJrdg/1-3.jpg",
      "https://i.ibb.co/mN9hYwv/1-2.jpg",
      "https://i.ibb.co/BP42fQY/1-1.jpg",
      "https://i.ibb.co/d2T6w4c/1-black-dress.jpg",
    ],
  },
  {
    id: 2,
    primaryImage: "https://i.ibb.co/xFHNfpy/2.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/6vHw627/2-3.jpg",
      "https://i.ibb.co/r0V4fc1/2-2.jpg",
      "https://i.ibb.co/tJ32Ntm/2-1.jpg",
      "https://i.ibb.co/xFHNfpy/2.jpg",
    ],
  },
  {
    id: 3,
    primaryImage: "https://i.ibb.co/ChQw18R/3-cream-dress.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/hsTkHRZ/3-3.jpg",
      "https://i.ibb.co/8McFqm6/3-2.jpg",
      "https://i.ibb.co/BKJtC6P/3-1.jpg",
      "https://i.ibb.co/ChQw18R/3-cream-dress.jpg",
    ],
  },
  {
    id: 4,
    primaryImage:
      "https://i.ibb.co/b7BH9sm/Primary-image-18-optimized-1000.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
  },
  {
    id: 5,
    primaryImage: "https://i.ibb.co/q1v7RDc/4-green-knot-dress.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/18BvxtD/4-1.jpg",
      "https://i.ibb.co/Zh01syg/4-3.jpg",
      "https://i.ibb.co/Km9tt21/4-4.jpg",
      "https://i.ibb.co/y5jhSHG/4-5.jpg",
    ],
  },
  {
    id: 6,
    primaryImage: "https://i.ibb.co/6Rq0mVB/5.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/WFPt1zN/5-1.jpg",
      "https://i.ibb.co/tYKKJR5/5-2.jpg",
      "https://i.ibb.co/0n2MdV8/5-3.jpg",
      "https://i.ibb.co/7J0tX84/5.jpg",
    ],
  },
  {
    id: 7,
    primaryImage: "https://i.ibb.co/zbhMfTF/6.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/p26htQf/6-3.jpg",
      "https://i.ibb.co/zfpDX46/6-2.jpg",
      "https://i.ibb.co/HrZBgyz/6-1.jpg",
      "https://i.ibb.co/zbhMfTF/6.jpg",
    ],
  },
  {
    id: 8,
    primaryImage: "https://i.ibb.co/3cVBrPc/7.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/Kq9wQRZ/7-1.jpg",
      "https://i.ibb.co/HNN8y8V/7-2.jpg",
      "https://i.ibb.co/6tKg9fd/7-3.jpg",
      "https://i.ibb.co/3cVBrPc/7.jpg",
    ],
  },
  {
    id: 9,
    primaryImage: "https://i.ibb.co/vZGQRjC/8-pink-ruffledress.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/MGgxPL3/8-1.jpg",
      "https://i.ibb.co/B4dbP75/8-3.jpg",
      "https://i.ibb.co/VLwdzmX/8-2.jpg",
      "https://i.ibb.co/vZGQRjC/8-pink-ruffledress.jpg",
    ],
  },
  {
    id: 10,
    primaryImage: "https://i.ibb.co/pyGpMsF/17.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/KVRTSWB/17-2.jpg",
      "https://i.ibb.co/zhK6wXP/17-1.jpg",
      "https://i.ibb.co/Z2CQ6RK/17-3.jpg",
      "https://i.ibb.co/pyGpMsF/17.jpg",
    ],
  },
  {
    id: 11,
    primaryImage: "https://i.ibb.co/cyTFHrB/9-blue-ikat-dress.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/THVvXqD/9-3.jpg",
      "https://i.ibb.co/Dg0rGYX/9-2.jpg",
      "https://i.ibb.co/nrzJ6ZQ/9-1.jpg",
      "https://i.ibb.co/cyTFHrB/9-blue-ikat-dress.jpg",
    ],
  },
  {
    id: 12,
    primaryImage: "https://i.ibb.co/V29Hk37/11-orange-dress.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/KV84GD6/11-3.jpg",
      "https://i.ibb.co/ZMqrfnh/11-2.jpg",
      "https://i.ibb.co/Kr3tRCN/11-1.jpg",
      "https://i.ibb.co/V29Hk37/11-orange-dress.jpg",
    ],
  },
  {
    id: 13,
    primaryImage: "https://i.ibb.co/c32PCcJ/12-orange-collar.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/VJZxJKW/12-2.jpg",
      "https://i.ibb.co/1nbTrJn/12-3.jpg",
      "https://i.ibb.co/0FSJRk7/12-1.jpg",
      "https://i.ibb.co/c32PCcJ/12-orange-collar.jpg",
    ],
  },
  {
    id: 14,
    primaryImage: "https://i.ibb.co/2S2ZSdk/10-red-plain-dress.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/NyfRWct/10-1.jpg",
      "https://i.ibb.co/vzP6RmL/10-3.jpg",
      "https://i.ibb.co/t8xz0v9/10-2.jpg",
      "https://i.ibb.co/2S2ZSdk/10-red-plain-dress.jpg",
    ],
  },
  {
    id: 15,
    primaryImage: "https://i.ibb.co/R7KvNvP/13.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/R7KvNvP/13.jpg",
      "https://i.ibb.co/2hWQGsp/13-1.jpg",
      "https://i.ibb.co/g7M1K9N/13-2.jpg",
      "https://i.ibb.co/wdtLHmF/13-4.jpg",
    ],
  },
  {
    id: 16,
    primaryImage: "https://i.ibb.co/YtWMjkm/14-yeloow-overlap.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    imgs: [
      "https://i.ibb.co/PGrzKtc/14-1.jpg",
      "https://i.ibb.co/LCSMBK6/14-2.jpg",
      "https://i.ibb.co/XspHf74/14-3.jpg",
      "https://i.ibb.co/YtWMjkm/14-yeloow-overlap.jpg",
    ],
  },
  {
    id: 17,
    primaryImage: "https://i.ibb.co/HrFHFCm/15.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
  },
  {
    primaryImage: "https://i.ibb.co/ykhRY87/16.jpg",
    price: "RS.550",
    collection: "SAATHI",
    category: "Short Kurtis",
    id: 18,
  },
  {
    primaryImage: "https://i.ibb.co/fGFrpW3/Primary-image.jpg",
    price: "RS.650",
    collection: "MERAKI",
    category: "Short Onepiece",
    id: 19,
  },
  {
    primaryImage: "https://i.ibb.co/2KMsg3G/Primary-image-1.jpg",
    price: "RS.650",
    collection: "MERAKI",
    category: "Short Onepiece",
    id: 20,
  },
  {
    primaryImage: "https://i.ibb.co/qF8ft5D/Primary-image-2.jpg",
    price: "650",
    collection: "MERAKI",
    category: "Short Onepiece",
    id: 21,
  },
  {
    primaryImage: "https://i.ibb.co/4pfs6t8/Primary-image-3.jpg",
    price: "RS.650",
    collection: "MERAKI",
    category: "Short Onepiece",
    id: 22,
  },
  {
    primaryImage: "https://i.ibb.co/QC0D5YY/Primary-image-4.jpg",
    price: "RS.650",
    collection: "MERAKI",
    category: "Short Onepiece",
    id: 23,
  },
  {
    primaryImage: "https://i.ibb.co/mvsWmtn/Primary-image-5.jpg",
    price: "RS.650",
    collection: "MERAKI",
    category: "Short Onepiece",
    id: 24,
  },
  {
    primaryImage: "https://i.ibb.co/YjX4fC2/Primary-image-6.jpg",
    price: "RS.650",
    collection: "MERAKI",
    category: "Short Onepiece",
    id: 25,
  },
  {
    primaryImage: "https://i.ibb.co/F5zwvqD/Primary-image-7.jpg",
    price: "RS.650",
    collection: "MERAKI",
    category: "Short Onepiece",
    id: 26,
  },
  {
    primaryImage: "https://i.ibb.co/ZYp72m5/Primary-image-8.jpg",
    price: "RS.650",
    collection: "MERAKI",
    category: "Short Onepiece",
    id: 27,
  },
  {
    primaryImage: "https://i.ibb.co/pwC0FWN/Primary-image-9.jpg",
    price: "RS.650",
    collection: "MERAKI",
    category: "Short Onepiece",
    id: 28,
  },
  {
    primaryImage: "https://i.ibb.co/Sm3SvZv/Primary-image-10.jpg",
    price: "RS.650",
    collection: "MERAKI",
    category: "Short Onepiece",
    id: 29,
  },
  {
    primaryImage: "https://i.ibb.co/L5LTrQ3/Primary-image-11.jpg",
    price: "RS.650",
    collection: "MERAKI",
    category: "Short Onepiece",
    id: 30,
  },
  {
    primaryImage: "https://i.ibb.co/Vt2dKnm/Primary-image-12.jpg",
    price: "RS.650",
    collection: "MERAKI",
    category: "Short Onepiece",
    id: 31,
  },
  {
    primaryImage: "https://i.ibb.co/xHtHv37/Primary-image-13.jpg",
    price: "RS.650",
    collection: "MERAKI",
    category: "Short Onepiece",
    id: 32,
  },
  {
    primaryImage: "https://i.ibb.co/h8ThJzn/8.jpg",
    price: "RS.850",
    collection: "MEHEK",
    category: "Long Onepiece",
    id: 33,
  },
  {
    primaryImage: "https://i.ibb.co/10JRVFh/3.jpg",
    price: "RS.750",
    collection: "MEHEK",
    category: "Short Onepiece",
    id: 34,
  },
  {
    primaryImage: "https://i.ibb.co/YdfWHVJ/7.jpg",
    price: "RS.1000",
    collection: "MEHEK",
    category: "Long Onepiece",
    id: 35,
  },
  {
    primaryImage: "https://i.ibb.co/Jtx4zsw/6.jpg",
    price: "RS.1000",
    collection: "MEHEK",
    category: "Long Onepiece",
    id: 36,
  },
  {
    primaryImage: "https://i.ibb.co/RHfpfsc/5.jpg",
    price: "RS.850",
    collection: "MEHEK",
    category: "Long Onepiece",
    id: 37,
  },
  {
    primaryImage: "https://i.ibb.co/p14Qzht/4.jpg",
    price: "RS.1000",
    collection: "MEHEK",
    category: "Long Onepiece",
    id: 38,
  },
  {
    primaryImage: "https://i.ibb.co/9pbH6s0/2.jpg",
    price: "RS.750",
    collection: "MEHEK",
    category: "Short Onepiece",
    id: 39,
  },
  {
    primaryImage: "https://i.ibb.co/VVt2Y0t/1.jpg",
    price: "RS.750",
    collection: "MEHEK",
    category: "Short Onepiece",
    id: 40,
  },
  {
    primaryImage: "https://i.ibb.co/yFwD10D/9.jpg",
    price: "RS.850",
    collection: "MEHEK",
    category: "Long Onepiece",
    id: 41,
  },
];
